//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_hoa_don
    {
        public int id { get; set; }
        public string ma_cthd { get; set; }
        public string ma_hoadon { get; set; }
        public string ma_mon { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
    }
}
