//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_vt
    {
        public int id { get; set; }
        public string ma_loaivt { get; set; }
        public string ten_loaivt { get; set; }
    }
}
