//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class quanLyCafeEntities : DbContext
    {
        public quanLyCafeEntities()
            : base("name=quanLyCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual DbSet<dvt> dvt { get; set; }
        public virtual DbSet<hoa_don> hoa_don { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<loai_mon> loai_mon { get; set; }
        public virtual DbSet<loai_nv> loai_nv { get; set; }
        public virtual DbSet<mon> mon { get; set; }
        public virtual DbSet<nha_cc> nha_cc { get; set; }
        public virtual DbSet<nhan_vien> nhan_vien { get; set; }
        public virtual DbSet<phan_quyen> phan_quyen { get; set; }
        public virtual DbSet<phieu_nhap_kho> phieu_nhap_kho { get; set; }
        public virtual DbSet<phieu_xuat_kho> phieu_xuat_kho { get; set; }
        public virtual DbSet<qui_doivt> qui_doivt { get; set; }
        public virtual DbSet<vat_tu> vat_tu { get; set; }
        public virtual DbSet<vmon> vmon { get; set; }
    
        public virtual int bao_cao_ct_hd(string ngay_tu, string ngay_den)
        {
            var ngay_tuParameter = ngay_tu != null ?
                new ObjectParameter("ngay_tu", ngay_tu) :
                new ObjectParameter("ngay_tu", typeof(string));
    
            var ngay_denParameter = ngay_den != null ?
                new ObjectParameter("ngay_den", ngay_den) :
                new ObjectParameter("ngay_den", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bao_cao_ct_hd", ngay_tuParameter, ngay_denParameter);
        }
    
        public virtual int bao_cao_hd(string ngay_tu, string ngay_den)
        {
            var ngay_tuParameter = ngay_tu != null ?
                new ObjectParameter("ngay_tu", ngay_tu) :
                new ObjectParameter("ngay_tu", typeof(string));
    
            var ngay_denParameter = ngay_den != null ?
                new ObjectParameter("ngay_den", ngay_den) :
                new ObjectParameter("ngay_den", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bao_cao_hd", ngay_tuParameter, ngay_denParameter);
        }
    
        public virtual int bao_cao_nhap_kho(string ma_vt, string ngay_tu)
        {
            var ma_vtParameter = ma_vt != null ?
                new ObjectParameter("ma_vt", ma_vt) :
                new ObjectParameter("ma_vt", typeof(string));
    
            var ngay_tuParameter = ngay_tu != null ?
                new ObjectParameter("ngay_tu", ngay_tu) :
                new ObjectParameter("ngay_tu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bao_cao_nhap_kho", ma_vtParameter, ngay_tuParameter);
        }
    
        public virtual int bao_cao_ton_kho(string ma_vt, string ngay_tu)
        {
            var ma_vtParameter = ma_vt != null ?
                new ObjectParameter("ma_vt", ma_vt) :
                new ObjectParameter("ma_vt", typeof(string));
    
            var ngay_tuParameter = ngay_tu != null ?
                new ObjectParameter("ngay_tu", ngay_tu) :
                new ObjectParameter("ngay_tu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bao_cao_ton_kho", ma_vtParameter, ngay_tuParameter);
        }
    
        public virtual int bao_cao_xuat_kho(string ma_vt, string ngay_tu)
        {
            var ma_vtParameter = ma_vt != null ?
                new ObjectParameter("ma_vt", ma_vt) :
                new ObjectParameter("ma_vt", typeof(string));
    
            var ngay_tuParameter = ngay_tu != null ?
                new ObjectParameter("ngay_tu", ngay_tu) :
                new ObjectParameter("ngay_tu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bao_cao_xuat_kho", ma_vtParameter, ngay_tuParameter);
        }
    
        public virtual int column_chart(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("column_chart", namParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
