//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon
    {
        public int id { get; set; }
        public string ma_mon { get; set; }
        public string ten_mon { get; set; }
        public string ma_loaiMon { get; set; }
        public Nullable<decimal> gia { get; set; }

}
}
