//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhan_vien
    {
        public int id { get; set; }
        public string ma_nv { get; set; }
        public string ten_nv { get; set; }
        public string dia_chi { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string ma_loainv { get; set; }
        public Nullable<double> he_so { get; set; }
        public string so_cmnd { get; set; }
        public string status { get; set; }
    }
}
