//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class phan_quyen
    {
        public int id { get; set; }
        public string tai_khoan { get; set; }
        public Nullable<bool> id1 { get; set; }
        public Nullable<bool> id2 { get; set; }
        public Nullable<bool> id3 { get; set; }
        public Nullable<bool> id4 { get; set; }
        public Nullable<bool> id5 { get; set; }
        public Nullable<bool> id6 { get; set; }
        public Nullable<bool> id7 { get; set; }
        public Nullable<bool> id8 { get; set; }
        public Nullable<bool> id9 { get; set; }
        public Nullable<bool> id10 { get; set; }
        public Nullable<bool> id11 { get; set; }
        public Nullable<bool> id12 { get; set; }
        public Nullable<bool> id13 { get; set; }
        public Nullable<bool> id14 { get; set; }
        public Nullable<bool> id15 { get; set; }
        public Nullable<bool> id16 { get; set; }
    }
}
