//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Management3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vat_tu
    {
        public int id { get; set; }
        public string ma_vt { get; set; }
        public string ten_vt { get; set; }
        public string ma_dvt { get; set; }
        public Nullable<decimal> gia_mua { get; set; }
        public string ma_loaivt { get; set; }
    }
}
